### ISSUE TITLE
Syntax error in KMLFormatter

### ISSUE THREAD

**Issue by DieterDePaepe** [tdt/core#359]
Line 154 of `app/Tdt/Core/Formatters/KMLFormatter.php` contains the code `if (!empty(@$array[$lat_long[2]]))`, which gives a syntax error on my PHP 5.4.16 installation.

**Comment by coreation** [comment]
Hi @DieterDePaepe  can you tell me which error that is exactly? I'm running 5.5 and don't have a VM atm ;)

**Comment by DieterDePaepe** [comment]
```
[2015-12-02 08:20:12] production.ERROR: exception 'Symfony\Component\Debug\Excep
tion\FatalErrorException' with message 'syntax error, unexpected '@'' in /opt/da
tatank/core/app/Tdt/Core/Formatters/KMLFormatter.php:154
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
```

**Comment by coreation** [comment]
Hey @DieterDePaepe This should fix that, tested it with an online php sandbox on 5.4. If this does the trick, close the issue :).

**Comment by DieterDePaepe** [comment]
After updating to `a61923b947` (from `2161e53`) I receive the following error:

```
[root@xxx]# php artisan migrate
PHP Fatal error:  Class 'Tdt\Input\InputServiceProvider' not found in /opt/datat
ank/core/bootstrap/compiled.php on line 4262
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","me
ssage":"Class 'Tdt\\Input\\InputServiceProvider' not found","file":"\/opt\/datat
ank\/core\/bootstrap\/compiled.php","line":4262}}[root@otn-dev core]# composer u
pdate
Warning: This development build of composer is over 60 days old. It is recommend
ed to update it by running "/usr/local/bin/composer self-update" to get the late
st version.
> php artisan clear-compiled
PHP Fatal error:  Class 'Tdt\Input\InputServiceProvider' not found in /opt/datat
ank/core/bootstrap/compiled.php on line 4262
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","me
ssage":"Class 'Tdt\\Input\\InputServiceProvider' not found","file":"\/opt\/datat
ank\/core\/bootstrap\/compiled.php","line":4262}}Script php artisan clear-compil
ed handling the pre-update-cmd event returned with an error



  [RuntimeException]
  Error Output: PHP Fatal error:  Class 'Tdt\Input\InputServiceProvider' not
  found in /opt/datatank/core/bootstrap/compiled.php on line 4262
```

**Comment by coreation** [comment]
That is to be expected yes, the composer file changed to integrate tdt/input into the core application. Normally a "composer update" should do the trick, then do migrate if that isn't triggered already by the update command. (it should be)

**Comment by coreation** [comment]
KML issue is fixed!

**Comment by DieterDePaepe** [comment]
Sorry for the late reply, only had time to check it out now.

Using version `28a6affdf`, I still get the same error when doing `composer update`:

    [xxx@xxx core]# composer update
    Warning: This development build of composer is over 60 days old. It is recommend
    ed to update it by running "/usr/local/bin/composer self-update" to get the late
    st version.
    > php artisan clear-compiled
    PHP Fatal error:  Class 'Tdt\Input\InputServiceProvider' not found in /opt/datat
    ank/core/bootstrap/compiled.php on line 4262
    {"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","me
    ssage":"Class 'Tdt\\Input\\InputServiceProvider' not found","file":"\/opt\/datat
    ank\/core\/bootstrap\/compiled.php","line":4262}}Script php artisan clear-compil
    ed handling the pre-update-cmd event returned with an error
    
    
      [RuntimeException]
      Error Output: PHP Fatal error:  Class 'Tdt\Input\InputServiceProvider' not
      found in /opt/datatank/core/bootstrap/compiled.php on line 4262
    
    
    update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock]
     [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
    progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
     [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--pre
    fer-lowest] [packages1] ... [packagesN]

You mentioned this could be due to a change in the composer file, but I don't see any reference to Tdt/Input in that file?

**Comment by coreation** [comment]
Oh, my bad I removed it by accident, a git pull should be ok now. Do a composer update --no-scripts if a normal update gives you the error.

**Comment by DieterDePaepe** [comment]
That did the trick. Still the same error, so I had to use the --no-scripts option. Datatank is working and KML is generated correctly.

I did get a warning after the composer update finished, I'm mentioning it to be complete:

    Writing lock file
    Generating autoload files
    Warning: Ambiguous class resolution, "Extract\Json" was found in both "/opt/data
    tank/core/vendor/tdt/input/src/models/Extract/Json.php" and "/opt/datatank/core/
    vendor/tdt/input/src/models/extract/Json.php", the first will be used.

**Comment by coreation** [comment]
Hm, that's odd, I remember the capital change a long while ago, Git+Mac had a hard time managing it but it got resolved nonetheless. Travis doesn't seem to give that warning either and the classes in the models are only the ones I'd expect (no double folders with the same name except a capital change). Can you check if there two folders in the models Extract and extract?

**Comment by DieterDePaepe** [comment]
There were 2 folders.
```
[xxx@xxx models]# cd Extract/
[xxx@xxx Extract]# ls
Csv.php  Json.php  Shp.php  Type.php  Xml.php
[xxx@xxx Extract]# cd ../extract/
[xxx@xxx extract]# ls
Json.php
```

After deleting the vendor folder and doing `composer install --no-scripts`, both folders are back.

I even tried deleting the cache entry from tdt/Input before the `composer install --no-scripts`, but this made no difference.

**Comment by DieterDePaepe** [comment]
Travis reports the same issue https://travis-ci.org/tdt/core/jobs/95338541 line 681:

```
Generating autoload files
Warning: Ambiguous class resolution, "Extract\Json" was found in both "/home/travis/build/tdt/core/vendor/tdt/input/src/models/Extract/Json.php" and "/home/travis/build/tdt/core/vendor/tdt/input/src/models/extract/Json.php", the first will be used.
Warning: Ambiguous class resolution, "Extract\Json" was found in both "/home/travis/build/tdt/core/vendor/tdt/input/src/models/Extract/Json.php" and "/home/travis/build/tdt/core/vendor/tdt/input/src/models/extract/Json.php", the first will be used.
```

This makes sense if you are on a mac: both names represent the same folder. But on a linux machine, the names represent 2 folders...

**Comment by coreation** [comment]
Ok, I knew Mac didn't really care about case sensitivity but I didn't know Git on Mac felt like it shouldn't list it in the folder structure either (or my Sublime didn't bother to show it which would be very unlikely). Hence the headscratching ;) Either way, I [removed it](https://github.com/tdt/input/tree/v2.0.0/src/models), it'll just take a bit of time for packagist to pick it up.
